99_cats_p2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: redirect('/cats')

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

99_cats_p2/app/views/layouts/_auth.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

99_cats_p2/app/views/layouts/_login.html.erb
<% if action == :logout %>
  <% action_url = session_url %>
  <% submit_value = "You're leaving us forever!" %>
  <% method_value = "POST" %>
<% else %>
  <% action_url = new_session_url %>
  <% submit_value = "Come join the Pawty" %>
  <% method_value = "GET" %>
<% end %>


<form action="<%= action_url %>" method="<%= method_value %>">

  <%= render 'layouts/auth'%>

  <% if action == :logout %>
    <input type="hidden" name="_method" value="DELETE">
  <% end %>

  <input type='submit' value='<%= submit_value %>'>

</form>

99_cats_p2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%if logged_in? %>
      <block style="float: right;">
        <%= current_user.username %>
        <br>
        <%= render 'layouts/login', action: :logout %>
        <br>
      </block>
    <% else %>
      <%= render 'layouts/login', action: :login %>
    <% end %>

    <% if flash[:errors].present? %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
    <br>
    <%= yield %>
  </body>
</html>